### PR TITLE
Updated READme.md file

### PR DESCRIPTION
**Pull request by Dorcastunmise**
A detailed READme.md suitable for app function.

### CODE REVIEW

**Comment by haseeb-xd** [comment]
> A detailed READme.md suitable for app function.

This is a android project. You haven't written the documentation properly. Please fix it accordingly

**Comment by Dorcastunmise** [comment]
What section do you want me to add or remove?

**Comment by Dorcastunmise** [comment]
Don't worry

**Comment by Dorcastunmise** [comment]
@haseeb-xd check the recent PR

**Comment by Dorcastunmise** [comment]
I'm waiting for a response @haseeb-xd

**Comment by Dorcastunmise** [comment]
Wheww !! Finally. By the way, I love the idea of your project @haseeb-xd. For real.

**Pull request merged**
